### PR TITLE
Fix GSC Toxic interaction with Baton Pass/Heal Bell

### LINKED ISSUE #3357: GSC Toxic is maintained with Baton Pass and Heal Bell
GSC suffers from some of the same Toxic oddities as RBY do, allthough only as a result of using Baton Pass or Heal Bell. Basically, Toxic and the Toxic counter is preserved when switching using Baton Pass. If whatever you are switching into is then poisoned or burned (or if it was when you switched into it), it will retain the Toxic status. It will also retain the count, unless the move was Toxic in which the counter is reset.

Leech Seed isn't affected, unlike RBY, only poison and burn is.

### PR DESCRIPTION
**Pull request by scheibo**
Fixes #3357

### CODE REVIEW

File: data/mods/gen2/statuses.js [hunk 1]
```diff
@@ -12,10 +12,16 @@ let BattleStatuses = {
 		},
 		onAfterMoveSelfPriority: 3,
 		onAfterMoveSelf(pokemon) {
-			this.damage(pokemon.maxhp / 8);
+			let toxicCounter = 1;
+			if (pokemon.volatiles['residualdmg']) {
+				pokemon.volatiles['residualdmg'].counter++;
+				toxicCounter = pokemon.volatiles['residualdmg'].counter;
+			}
+			this.damage(this.clampIntRange(Math.floor(pokemon.maxhp / 8), 1) * toxicCounter, pokemon);
```
Comment (scheibo) [inline data/mods/gen2/statuses.js]: Copied this logic from gen1, though I had some questions

- it doesn't cap the counter, but I assume this doesn't matter (below, the `effectData.stage` was capped to 15)
- it clamps the range - I think this is desirable
- I've added a hint after @Zarel asked. Should Gen 1 do this as well, or is Toxic's glitchiness well enough understood in that gen that its redundant? I purposefully placed the `-hint` so that it occurs after the `damage` message in the log, as opposed to issuing it above when we already know `toxicCounter > `.
- is it correct that the counter is only increased/applied in `onAfterMoveSelf` and not `onAfterSwitchSelf` in both gens?

Comment (Zarel) [reply data/mods/gen2/statuses.js]: I'd like a hint in Gen 1, too. PS generally needs more hints.

**Comment by Zarel** [comment]
Does the residual damage counter reset on switch-out? I don't remember the report touching on that.

File: data/mods/gen2/statuses.js (hunk 1 above)
Comment (Marty-D) [reply data/mods/gen2/statuses.js]: > 
> 
> Copied this logic from gen1, though I had some questions
> 
>     * it doesn't cap the counter, but I assume this doesn't matter

This is correct; the Toxic counter only started being capped to 15 in Gen 3.
>     * is it correct that the counter is only increased/applied in `onAfterMoveSelf` and not `onAfterSwitchSelf` in both gens?

If a previously burned/poisoned Pokemon is switched in with Baton Pass from a Pokemon with a Toxic counter, it immediately takes `1/16 * X` damage (even though regular poison and burn is 1/8 max HP in Gen 2). If they get passed a Toxic counter and get burned or poisoned later, it's also `1/16 * X`, where X is whatever the previous counter was + 1 no matter how many turns have passed.

Unless I'm misunderstanding, `onAfterSwitchSelf` isn't relevant in Gen 1 because Baton Pass doesn't exist.

**Comment by scheibo** [comment]
> I'd like a hint in Gen 1, too. PS generally needs more hints.

[On it.](https://github.com/Zarel/Pokemon-Showdown/issues/5242)

> If a previously burned/poisoned Pokemon is switched in with Baton Pass from a Pokemon with a Toxic counter, it immediately takes 1/16 * X damage (even though regular poison and burn is 1/8 max HP in Gen 2). If they get passed a Toxic counter and get burned or poisoned later, it's also 1/16 * X, where X is whatever the previous counter was + 1 no matter how many turns have passed.

Gotcha. So the toxic counter kind of 'ruins' the original status's damage and forces it to behave like toxic would.

> Unless I'm misunderstanding, onAfterSwitchSelf isn't relevant in Gen 1 because Baton Pass doesn't exist.

I've taken the liberty of deleting it from the Gen 1 code then given we don't think its going to actually occur (no point in retaining dead code).

> Does the residual damage counter reset on switch-out? I don't remember the report touching on that.

Oh, you're right, that wasn't covered. I'm going to take a guess and assume it goes away completely through a normal switch, just like how Toxic reverts to regular poison  (I've modified the code to behave that way). @Marty-D, is that correct?

File: data/mods/gen2/statuses.js [hunk 2]
```diff
@@ -226,6 +223,31 @@ let BattleStatuses = {
...
 };
 
+/**
+ * @param {Battle} battle
+ * @param {Pokemon} pokemon
+ */
+function residualdmg(battle, pokemon) {
+	if (pokemon.volatiles['residualdmg']) {
+		battle.damage(battle.clampIntRange(Math.floor(pokemon.maxhp / 16) * pokemon.volatiles['residualdmg'].counter, 1), pokemon);
+		battle.add('-hint', 'In GSC, Toxic\'s counter is retained through Baton Pass/Heal Bell and applies to PSN/BRN.');
```
Comment (scheibo) [inline data/mods/gen2/statuses.js]: Actually, not sure about this hint - we probably only want to show it the first time this happens, not every turn of residual damage.

**Comment by Marty-D** [comment]
> > Unless I'm misunderstanding, onAfterSwitchSelf isn't relevant in Gen 1 because Baton Pass doesn't exist.
> 
> I've taken the liberty of deleting it from the Gen 1 code then given we don't think its going to actually occur (no point in retaining dead code).

Oh, really sorry for the confusion but I was answering your question about whether or not the Toxic counter increases there, not switches in general. `onAfterSwitchInSelf` is definitely needed in Gen 1 for those statuses.
> > Does the residual damage counter reset on switch-out? I don't remember the report touching on that.
> 
> Oh, you're right, that wasn't covered. I'm going to take a guess and assume it goes away completely through a normal switch, just like how Toxic reverts to regular poison (I've modified the code to behave that way). @Marty-D, is that correct?

Yep, normal switching removes the counter.

**Comment by scheibo** [comment]
> `onAfterSwitchInSelf` is definitely needed in Gen 1 for those statuses.

Reverted back.

File: data/mods/gen2/statuses.js (hunk 2 above)
Comment (scheibo) [reply data/mods/gen2/statuses.js]: Added logic such that we only `-hint` once about this per battle (as well as created the `hint` method on Battle, which also supports one-sided hints which will be useful for #5242 or #5222).

File: sim/battle.ts [hunk 3]
```diff
@@ -2987,6 +2989,24 @@ export class Battle extends Dex.ModdedDex {
 		return false;
 	}
 
+	hint(hint: string, once?: boolean, sideid?: 'p1'|'p2') {
```
Comment (Zarel) [inline sim/battle.ts]:
```suggestion
	hint(hint: string, once?: boolean, sideid?: 'p1' | 'p2') {
```

Here's your Travis error.

**Comment by Zarel** [comment]
@Marty-D?

**Comment by Marty-D** [comment]
The counter should be paused while the Pokemon doesn't have a damaging status condition. If something is badly poisoned, takes 3 turns of Toxic damage, then uses Baton Pass into something that isn't statused, then 3 more turns pass, then this new Pokemon gets burned, its next residual damage will be 1/16 * 4. Likewise, in the same situation except the Baton Pass is into a Pokemon that is already burned or poisoned, it immediately takes the 1/16 * 4.

**Comment by scheibo** [comment]
> The counter should be paused while the Pokemon doesn't have a damaging status condition.
Done

File: data/mods/gen2/statuses.js [hunk 4]
```diff
@@ -226,6 +223,31 @@ let BattleStatuses = {
...
+		name: 'residualdmg',
+		id: 'residualdmg',
+		num: 0,
+		onStart(target) {
+			target.volatiles['residualdmg'].counter = 0;
+		},
+		onAfterMoveSelfPriority: 100,
+		onAfterMoveSelf(pokemon) {
+			if (['brn', 'psn', 'tox'].includes(pokemon.status)) pokemon.volatiles['residualdmg'].counter++;
+		},
```
Comment (Marty-D) [inline data/mods/gen2/statuses.js]: I think the last thing to do then would be increasing the counter during `onAfterSwitchInSelf` here as well. Currently 3 turns of Toxic Baton Passing into an already burned Pokemon keeps the counter at 3 for the switch turn.

Comment (scheibo) [reply data/mods/gen2/statuses.js]: Done!

File: sim/battle.ts (hunk 3 above)
Comment (urkerab) [inline sim/battle.ts]: Out of interest, why are you using a sideid here? I would have thought a Side would make more sense (and also simplify the code slightly, see Pokemon.getHeathInner).

Comment (scheibo) [reply sim/battle.ts]: I agree, it would be simpler. I'll update it in a future commit.
