### PR TITLE
Remove .js extension from requires

### LINKED ISSUE #2722: Inconsistent use of extension when `require`ing js files.
When examining `simulator.js`, we see that both `ProcessManager` and `BattleEngine` use require without specifying the extension. `const ProcessManager = require('./process-manager');` However, later on in the file, `crashlogger.js` is required with the `js` extension. This is inconsistent.

I think that it should be consistent across the project. If we chose to leave off the extension, individuals can take advantage of their tools resolution system to resolve the file differently. This allows developers to "override" files that highly dependent on the platform.

Suppose I want to use `battle-engine.js` in the browser and I have a webpack config that resolves `es6` files with higher priority than `js` files. I can now override `require('./crashlogger')` in `Battle.prototype.leave` to my own implementation as I choose. I can use a similar method to create a `tools.es6` that has all `this.data` built into it and define `global.Tools` for `battle-engine.js` to run in the browser. 

If the developers think this is a good idea, I am willing to make a PR with the changes.

### PR DESCRIPTION
**Pull request by taylor1791**
Resolves #2722

Motivation taken from #2722 

Suppose I want to use battle-engine.js in the browser and I have a webpack config that resolves es6 files with higher priority than js files. I can now override require('./crashlogger') in Battle.prototype.leave to my own implementation as I choose. I can use a similar method to create a tools.es6 that has all this.data built into it and define global.Tools for battle-engine.js to run in the browser.

### CODE REVIEW

**Comment by panpawn** [comment]
yay for standardization

**Comment by taylor1791** [comment]
Working on fixing the Travis build.

**Comment by Morfent** [comment]
Don't forget to run `npm test` before you make a pullreq or force push to make updates for it.

**Comment by taylor1791** [comment]
Build passes. Should be ready for those with Compound Eyes. Sorry bad joke.

File: tools.js [hunk 1]
```diff
@@ -112,7 +112,7 @@ module.exports = (() => {
 			if (maybeScripts.code !== 'MODULE_NOT_FOUND') throw new Error("CRASH LOADING DATA IN " + path + ": " + maybeScripts.stack);
 		} else {
 			let BattleScripts = maybeScripts.BattleScripts;
-			if (!BattleScripts || typeof BattleScripts !== 'object') throw new TypeError("Exported property `BattleScripts`from `./data/scripts.js` must be an object except `null`.");
+			if (!BattleScripts || typeof BattleScripts !== 'object') throw new TypeError("Exported property `BattleScripts`from `./data/scripts` must be an object except `null`.");
```
Comment (Slayer95) [inline tools.js]: Probably we should keep the extension here

File: app.js [hunk 2]
```diff
@@ -71,29 +71,29 @@ try {
...
 		fs.readFileSync(path.resolve(__dirname, 'config/config-example.js'))
 	);
 } finally {
-	global.Config = require('./config/config.js');
+	global.Config = require('./config/config');
 }
 
 if (Config.watchconfig) {
-	fs.watchFile(path.resolve(__dirname, 'config/config.js'), (curr, prev) => {
+	fs.watchFile(path.resolve(__dirname, 'config/config'), (curr, prev) => {
```
Comment (Slayer95) [inline app.js]: Keep the extension here.

Or, if you want to deal with this in a extension-agnostic way, pass the resolved module path

**Comment by Slayer95** [comment]
Please keep the extension in the error messages and logs...

File: test/simulator/index.js [hunk 3]
```diff
@@ -7,7 +7,7 @@ function loadTests(desc, dir) {
 	let contents = fs.readdirSync(path.join(__dirname, dir));
 	describe(desc, function () {
 		for (let i = 0; i < contents.length; i++) {
-			if (contents[i].substr(-3) === '.js') require('./' + path.join(dir, contents[i]));
+			if (contents[i].substr(-3) === '.js') require('./' + path.join(dir, contents[i].substr(0, contents[i].length - 3)));
```
Comment (Slayer95) [inline test/simulator/index.js]: Does this change actually make sense?

Comment (taylor1791) [inline test/simulator/index.js]: I think so. Assume we have the same resolution pattern described above and `contents = ['hello.js', 'hello.es6']`. It will skip `hello.es6`, and run `require('./<div>/hello')` and actually load `hello.es6`.

That being said, I don't know how often people will want to override the tests. It would also require the user to customize the mocha options. The use for this is drastically lower than the non-test code.

If you want me to leave this line alone, just say the magic words.

**Comment by taylor1791** [comment]
I changed the logs back, "passed the resolved module path", and removed the change to `test/simulator/index.js`.

File: app.js [hunk 4]
```diff
@@ -81,15 +81,16 @@ try {
 		fs.readFileSync(path.resolve(__dirname, 'config/config-example.js'))
 	);
 } finally {
-	global.Config = require('./config/config.js');
+	global.Config = require('./config/config');
 }
 
 if (Config.watchconfig) {
-	fs.watchFile(path.resolve(__dirname, 'config/config.js'), (curr, prev) => {
+	let configPath = require.resolve(path.resolve(__dirname, 'config/config'));
```
Comment (Slayer95) [inline app.js]: This simplifies to ``require.resolve('./config/config.js');``

Comment (taylor1791) [inline app.js]: Fixed.
