### PR TITLE
Fixes for target resolution

### LINKED ISSUE #5361: Imprison and Snatch targetting is broken
A. Steps
1. Use Imprison
2. Try to use any move
3. See that you actually Struggle

B. Steps
1. Doubles: Use Snatch and an snatchable move
2. See that a slow foe Pokémon snatches the move

### LINKED ISSUE #5362: Redirection should work if the player targeted an empty ally slot
From https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-435642464

### PR DESCRIPTION
**Pull request by Slayer95**
- Storm Drain and Lightningrod now redirect attacks originally targetted against an empty allied slot of the attacker.
- Imprison and Snatch no longer affect both ``self`` and ``foeSide``.

Fixes #5361 and fixes #5362.

### CODE REVIEW

File: sim/battle.ts [hunk 1]
```diff
@@ -2185,16 +2185,13 @@ export class Battle extends Dex.ModdedDex {
 			} else {
 				target = pokemon.side.active[-targetLoc - 1];
 			}
-			if (target) {
-				if (!target.fainted) {
-					// target exists and is not fainted
-					return target;
-				} else if (target.side === pokemon.side) {
-					// fainted allied targets don't retarget
```
Comment (Zarel) [inline sim/battle.ts]: Is this wrong?

File: sim/pokemon.ts [hunk 2]
```diff
@@ -560,8 +560,10 @@ export class Pokemon {
 		return this.foes().filter(foe => this.battle.isAdjacent(this, foe));
 	}
 
-	getMoveTargets(move: Move, target: Pokemon): Pokemon[] {
+	getMoveTargets(move: Move, target: Pokemon): {hit: Pokemon[], pp: Pokemon[]} {
```
Comment (Zarel) [inline sim/pokemon.ts]: I feel like `pressureTargets` is a better name than `pp`.

`targets`, `pressureTargets`.

File: sim/battle.ts (hunk 1 above)
Comment (Slayer95) [reply sim/battle.ts]: They don't retarget by default, but still can be redirected by Storm Drain / Lightningrod.

**Comment by Slayer95** [comment]
Updated~

File: sim/pokemon.ts [hunk 3]
```diff
@@ -610,11 +615,12 @@ export class Pokemon {
 			if (move.pressureTarget) {
 				// At the moment, this is the only supported target.
 				if (move.pressureTarget === 'foeSide') {
-					targets.push(...this.foes());
```
Comment (Slayer95) [inline sim/pokemon.ts]: I must say that it's baffling that this used to work...

File: sim/battle.ts (hunk 1 above)
Comment (Slayer95) [reply sim/battle.ts]: BTW, it might be unclear, but this diff is equivalent to just changing the ``return null`` for ``return target``.

Comment (Zarel) [reply sim/battle.ts]: Is the prevent-retargeting code done elsewhere or something?

File: data/mods/gen3/scripts.js [hunk 4]
```diff
@@ -71,11 +71,11 @@ let BattleScripts = {
 			return false;
 		}
 
-		const targets = pokemon.getMoveTargets(move, target);
+		const {targets, ppTargets} = pokemon.getMoveTargets(move, target);
```
Comment (Zarel) [inline data/mods/gen3/scripts.js]: I said `pressureTargets` because I think "pp" is unnecessarily vague. How am I supposed to figure it out means `targetsForThePurposesOfCalculatingAdditionalPPDeductionFromEffects`? Pressure is _waaaayyyyy_ clearer.

File: sim/battle.ts (hunk 1 above)
Comment (Zarel) [reply sim/battle.ts]: Oh, I understand now.

File: sim/battle.ts [hunk 5]
```diff
@@ -2185,16 +2185,13 @@ export class Battle extends Dex.ModdedDex {
...
-					return null;
-				}
+			if (target && !(target.fainted && target.side !== pokemon.side)) {
+				// We aren't targetting a fainted foe.
```
Comment (Zarel) [inline sim/battle.ts]: Then this comment is wrong.

Comment (Zarel) [reply sim/battle.ts]: We could even do the checks separately!

Comment (Slayer95) [reply sim/battle.ts]: Wrong how?

Comment (Zarel) [reply sim/battle.ts]:
```suggestion
				// Target is unfainted: no need to retarget
				// Or target is a fainted ally: attack shouldn't retarget
```

**Comment by Slayer95** [comment]
Updated ~

**Comment by Zarel** [comment]
Thanks!
